/*
 * File: app/view/ExcView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsosStatus.view.ExcView', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    cls: 'ExcDetView',
    height: 150,
    id: 'ExcView',
    itemId: 'ExcView',
    maxHeight: 150,
    minHeight: 150,
    width: 350,
    bodyPadding: 10,
    frameHeader: false,
    header: false,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    id: 'excType',
                    itemId: 'excType',
                    fieldLabel: 'Type',
                    labelWidth: 60,
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    id: 'excProcess',
                    itemId: 'excProcess',
                    fieldLabel: 'process',
                    labelWidth: 60,
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    id: 'excDate',
                    itemId: 'excDate',
                    width: 320,
                    fieldLabel: 'Date',
                    labelWidth: 60,
                    readOnly: true
                },
                {
                    xtype: 'textareafield',
                    height: 45,
                    id: 'excDetails',
                    itemId: 'excDetails',
                    width: 320,
                    fieldLabel: 'Details',
                    labelWidth: 60,
                    readOnly: true
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    cls: 'check',
                    id: 'verified',
                    itemId: 'verified',
                    maxWidth: 100,
                    minWidth: 100,
                    width: 100,
                    fieldLabel: '',
                    labelWidth: 0,
                    boxLabel: 'Verified'
                },
                {
                    xtype: 'button',
                    cls: 'delete',
                    height: 24,
                    id: 'delete',
                    itemId: 'delete',
                    maxHeight: 24,
                    minHeight: 24,
                    minWidth: 100,
                    text: 'DELETE'
                }
            ]
        });

        me.callParent(arguments);
    }

});