/*
 * File: app/view/contacts.js
 * Date: Thu Apr 05 2012 15:30:43 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.contacts', {
    extend: 'istsos.view.ui.contacts',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});