/*
 * File: app/view/FormDataQuality.js
 * Date: Wed Dec 28 2011 16:21:09 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.FormDataQuality', {
    extend: 'istsos.view.ui.FormDataQuality',

    initComponent: function() {
        var me = this;
        var store = Ext.create('istsos.store.DataQualityStore');
        me.callParent(arguments);
    }
});