/*
 * File: app/view/paths.js
 * Date: Wed Apr 11 2012 11:03:45 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.paths', {
    extend: 'istsos.view.ui.paths',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },
    test: function() {
        console.log("ciao genio: Arg: " + arguments);
    }
});