/*
 * File: app/view/serviceurl.js
 * Date: Fri Apr 20 2012 14:33:11 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.serviceurl', {
    extend: 'istsos.view.ui.serviceurl',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});