/*
 * File: app/view/Wizard.js
 * Date: Wed Apr 04 2012 18:12:58 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.Wizard', {
    extend: 'istsos.view.ui.Wizard',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});