/*
 * File: app/controller/excDetailsController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsosStatus.controller.excDetailsController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'ExcDetView',
            selector: '#excDetView'
        }
    ],

    onButtonClick: function(button, e, eOpts) {
            var r = false;

            console.log(button);

            if(typeof(exc.id)  !== 'undefined')
                r=confirm("Press a button");

            if (r===true) {

                Ext.Ajax.request({
                    url: '/istsos/wa/istsos/services/'+ service +'/logs?id='+ button.id,
                    success: function(){ alert('Exceptions ' + exc.id +' removed');},
                    method: 'DELETE'
                });

            } else {

                if(typeof(exc.id)  === 'undefined')
                    alert('Exception not defined');
                else
                    console.log('NOT confirmed');
            }
    },

    onFormBeforeRender: function(component, eOpts) {
            console.log(component);

            exc = component.extraParams.d;
            id  = component.extraParams.id;

            console.log(exc);
            console.log(id);

            if(exc.status === 'verified'){
                var ver = component.getComponent('verified');
                ver.setValue(true);
            }

            component.getComponent('excType').setValue(exc.message);
            component.getComponent('excProcess').setValue(exc.process);
            component.getComponent('excDate').setValue(exc.datetime);
            component.getComponent('excDetails').setValue(exc.details);


            component.getComponent('verified').on('change',this.onChange);


    },

    init: function(application) {
        this.control({
            "button": {
                click: this.onButtonClick
            },
            "#ExcDetView": {
                beforerender: this.onFormBeforeRender
            }
        });
    },

    onLaunch: function() {
            _excDetController = this;
    },

    onChange: function(field, newValue, oldValue, eOpts) {

                    var status = 'pending';
                    var r = false;

                    if(newValue === true)
                        status = 'verified';

                    if(typeof(exc.id)  !== 'undefined')
                        r=confirm("Press a button");

                    if (r===true ) {

                        var id = this.id.split(' ')[1];

                        Ext.Ajax.request({
                            url: '/istsos/wa/istsos/services/'+ service +'/logs',
                            jsonData: {
                                id: id,
                                newstatus: status
                            },
                            success: function(){ alert('New Status set');},
                            method: 'PUT'
                        });

                    } else {
                        if(typeof(exc.id) !== 'undefined'){
                            alert('No exception!!!');

                        }else
                            alert('No exception found');

                        field.un('change',_excDetController.onChange);
                        field.setValue(oldValue);
                        field.on('change',_excDetController.onChange);
                    }
    }

});
