/*
 * File: app/controller/execController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsosStatus.controller.execController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'Execview',
            selector: '#ExecView'
        }
    ],

    init: function(application) {
            this.control({
                '#ExecView':{
                    show: this.onShow
                }
            });
    },

    onShow: function(param) {

            var d = param.extraParams.d;

            Ext.getCmp('execView').setTitle(d.name);

            Ext.getCmp('lastObs').setValue(d.lastObservation);
            Ext.getCmp('lastMes').setValue(d.lastMeasure + " " + d.oum);
            Ext.getCmp('op').setValue(d.parent.parent.name);
            Ext.getCmp('status').setValue(d.parent.name);

           for(var i = d.exceptions.length -1 ; i >= 0; i--){

                var myForm = Ext.create('istsosStatus.view.ExcDetView');

                exc = d.exceptions[i];
                id = 'exc_'+ i;
                myForm.extraParams = {d: exc, id:id};

                myForm.id = id;

                myForm.getComponent('verified').id = 'verified ' + exc.id;

                myForm.getComponent('excType').id = 'excType' + id;
                myForm.getComponent('excProcess').id = 'excProcess'+ id;
                myForm.getComponent('excDate').id = 'excDate'+ id;
                myForm.getComponent('excDetails').id = 'excDetails'+id;


                Ext.getCmp('exception').add(myForm);
           }
    }

});
