/*
 * File: app/view/ui/CheckColumn.js
 * Date: Fri Dec 13 2013 10:53:43 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.CheckColumn', {
    extend: 'Ext.grid.column.Column',

    text: 'Interpolation',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});