/*
 * File: app/view/ui/CheckColumn.js
 * Date: Mon Sep 02 2013 10:49:22 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.CheckColumn', {
    extend: 'Ext.grid.column.Column',

    text: 'Interpolation',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});