/*
 * File: app/view/ui/MyGridPanel15.js
 * Date: Fri Jul 06 2012 10:15:34 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.MyGridPanel15', {
    extend: 'Ext.grid.Panel',

    height: 250,
    width: 400,
    title: 'My Grid Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String',
                    field: {
                        xtype: 'combobox',
                        fieldLabel: 'Label'
                    }
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.CellEditing', {

                })
            ]
        });

        me.callParent(arguments);
    }
});