/*
 * File: app/view/ui/paths.js
 * Date: Fri Dec 13 2013 10:53:43 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.paths', {
    extend: 'Ext.form.Panel',

    border: 0,
    bodyPadding: 10,
    bodyStyle: 'centerBody',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    name: 'istsos',
                    fieldLabel: 'istSOS lib',
                    anchor: '100%'
                },
                {
                    xtype: 'textfield',
                    name: 'services',
                    fieldLabel: 'istSOS config',
                    anchor: '100%'
                }
            ]
        });

        me.callParent(arguments);
    }
});