/*
 * File: app/view/ui/ProcedureGrid.js
 * Date: Tue Jun 18 2013 16:52:26 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.ProcedureGrid', {
    extend: 'Ext.panel.Panel',

    border: 0,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});