/*
 * File: app/view/ui/VirtualProcedureEditor.js
 * Date: Tue Sep 03 2013 18:36:29 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.VirtualProcedureEditor', {
    extend: 'Ext.panel.Panel',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Virtual procedure',
                            labelWidth: 150,
                            anchor: '100%'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    activeItem: 0,
                    title: '',
                    activeTab: 0,
                    flex: 1,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Rating curve',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Add row'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Remove selected'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    border: 0,
                                    title: '',
                                    flex: 1,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            flex: 1,
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    }
                                },
                                {
                                    xtype: 'panel',
                                    border: 0,
                                    height: 60,
                                    layout: {
                                        align: 'stretch',
                                        padding: '8px 0px 8px 0px',
                                        type: 'hbox'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Delete',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            width: 40
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Save',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Code',
                            items: [
                                {
                                    xtype: 'panel',
                                    border: 0,
                                    title: '',
                                    flex: 1
                                },
                                {
                                    xtype: 'panel',
                                    border: 0,
                                    height: 60,
                                    layout: {
                                        align: 'stretch',
                                        padding: '8px 0px 8px 0px',
                                        type: 'hbox'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Delete',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            width: 40
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Save',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});