/*
 * File: app/view/ui/Wizard.js
 * Date: Tue Apr 10 2012 16:56:38 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsos.view.ui.Wizard', {
    extend: 'Ext.panel.Panel',

    id: 'wizard',
    activeItem: 0,
    layout: {
        type: 'border'
    },
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    height: 40,
                    dock: 'bottom',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            scale: 'medium',
                            text: '<< Back'
                        },
                        {
                            xtype: 'button',
                            scale: 'medium',
                            text: 'Next >>'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    title: 'My Panel',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    height: 150,
                    title: '',
                    region: 'north'
                }
            ]
        });

        me.callParent(arguments);
    }
});