/*
 * File: app/view/geo.js
 * Date: Tue Apr 17 2012 17:03:01 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.geo', {
    extend: 'istsos.view.ui.geo',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
        if (this.istService!='default') {
            Ext.getCmp('defaultepsg').setReadOnly(true);
        }
    }
});