/*
 * File: app/view/identification.js
 * Date: Thu Apr 12 2012 09:08:03 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.identification', {
    extend: 'istsos.view.ui.identification',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});