/*
 * File: app/view/MyGridPanel15.js
 * Date: Fri Jul 06 2012 10:15:34 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.MyGridPanel15', {
    extend: 'istsos.view.ui.MyGridPanel15',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});