/*
 * File: app/view/VirtualProcedureEditor.js
 * Date: Tue Sep 03 2013 18:36:29 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('istsos.view.VirtualProcedureEditor', {
    extend: 'istsos.view.ui.VirtualProcedureEditor',
    alias: 'widget.virtualprocedureeditor',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});