/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('requests.view.HomePanel', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.TextArea'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            height: 80,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: '',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'servicescmb',
                                            fieldLabel: '',
                                            emptyText: 'Choose the istSOS instance',
                                            displayField: 'service',
                                            store: 'Services',
                                            valueField: 'service'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            id: 'serviceurl',
                                            fieldLabel: '',
                                            emptyText: 'Same origin url..'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    width: 180,
                                    bodyStyle: {
                                        background: 'transparent url(images/istsos-logo.png) no-repeat scroll center center',
                                        'background-size': 'contain'
                                    },
                                    title: '',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            frame: false,
                            layout: 'accordion',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'OGC - SOS 1.0.0',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    bodyPadding: 10,
                                                    title: '',
                                                    items: [
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            fieldLabel: '',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    id: 'sosmethod',
                                                                    width: 156,
                                                                    fieldLabel: 'Method',
                                                                    labelWidth: 50,
                                                                    displayField: 'name',
                                                                    queryMode: 'local',
                                                                    store: 'Methods',
                                                                    valueField: 'name'
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    flex: 1,
                                                                    id: 'sosrequests',
                                                                    fieldLabel: 'Requests',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 70,
                                                                    displayField: 'name',
                                                                    queryMode: 'local',
                                                                    store: 'Requests',
                                                                    valueField: 'id'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    id: 'sosmethodpanel',
                                                    layout: 'card',
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            id: 'sosgetter',
                                                            title: '',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'form',
                                                                    margins: '8px',
                                                                    frame: true,
                                                                    id: 'sosGetForm',
                                                                    width: 450,
                                                                    title: 'GET Parameters',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            layout: {
                                                                                type: 'hbox',
                                                                                align: 'stretchmax',
                                                                                pack: 'center'
                                                                            },
                                                                            items: [
                                                                                {
                                                                                    xtype: 'button',
                                                                                    flex: 1,
                                                                                    id: 'sendsosget',
                                                                                    text: 'SEND'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    margins: '8px',
                                                                    frame: true,
                                                                    html: '<pre id="presosgetresult" class="prettyprint" style="border: none;"></pre>',
                                                                    id: 'sosgetresult',
                                                                    autoScroll: true,
                                                                    bodyPadding: '16px',
                                                                    title: 'Result'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            itemId: 'sosposter',
                                                            layout: 'accordion',
                                                            title: '',
                                                            items: [
                                                                {
                                                                    xtype: 'form',
                                                                    width: 450,
                                                                    layout: 'fit',
                                                                    bodyPadding: 10,
                                                                    title: 'POST XML Body',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'toolbar',
                                                                            dock: 'top',
                                                                            layout: {
                                                                                type: 'hbox',
                                                                                align: 'stretchmax',
                                                                                pack: 'center'
                                                                            },
                                                                            items: [
                                                                                {
                                                                                    xtype: 'button',
                                                                                    flex: 1,
                                                                                    id: 'sendsospost',
                                                                                    text: 'SEND'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ],
                                                                    items: [
                                                                        {
                                                                            xtype: 'textareafield',
                                                                            id: 'sospostbody',
                                                                            fieldLabel: ''
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    html: '<pre id="presospostresult" class="prettyprint" style="border: none;"></pre>',
                                                                    id: 'sosPostResult',
                                                                    autoScroll: true,
                                                                    bodyPadding: '16px',
                                                                    title: 'Result'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    disabled: true,
                                    title: 'WA REST'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});