/*
 * File: app/view/ui/testColumn.js
 * Date: Tue Mar 20 2012 10:10:02 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.testColumn', {
    extend: 'Ext.panel.Panel',

    height: 538,
    width: 702,
    layout: {
        type: 'fit'
    },
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'chart',
                    height: 250,
                    width: 400,
                    animate: true,
                    insetPadding: 20,
                    store: 'testcolumnstore',
                    axes: [
                        {
                            type: 'Category',
                            fields: [
                                'isodate'
                            ],
                            position: 'bottom',
                            title: 'Time'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'value'
                            ],
                            position: 'left',
                            title: 'Temperature'
                        }
                    ],
                    series: [
                        {
                            type: 'column',
                            label: {
                                display: 'insideEnd',
                                field: 'y',
                                color: '#333',
                                'text-anchor': 'middle'
                            },
                            xField: 'x',
                            yField: [
                                'y'
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});