/*
 * File: designer.js
 * Date: Mon Sep 02 2013 14:02:44 GMT+0200 (CEST)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'istsos',

    stores: [
        'DataQualityStore',
        'Offerings',
        'Procedures',
        'ObservedProperties',
        'Observations',
        'serverstatus',
        'Fake',
        'Constraint',
        'cmbIdentification',
        'cmbSml',
        'gridOutputs',
        'cmbSystemType',
        'cmbName',
        'cmbNameDescription',
        'Services',
        'gridDocumentation',
        'cmbDocumentFormat',
        'gridProceduresList',
        'gridObservedProperties',
        'gridUoms',
        'gridOfferings',
        'MyArrayStore'
    ],

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('istsos.view.MainPanel', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
        var cmp2 = Ext.create('istsos.view.BasePage', {
            renderTo: Ext.getBody()
        });
        cmp2.show();
        var cmp3 = Ext.create('istsos.view.contactinfo', {
            renderTo: Ext.getBody()
        });
        cmp3.show();
        var cmp4 = Ext.create('istsos.view.paths', {
            renderTo: Ext.getBody()
        });
        cmp4.show();
        var cmp5 = Ext.create('istsos.view.about', {
            renderTo: Ext.getBody()
        });
        cmp5.show();
        var cmp6 = Ext.create('istsos.view.contacts', {
            renderTo: Ext.getBody()
        });
        cmp6.show();
        var cmp7 = Ext.create('istsos.view.identification', {
            renderTo: Ext.getBody()
        });
        cmp7.show();
        var cmp8 = Ext.create('istsos.view.provider', {
            renderTo: Ext.getBody()
        });
        cmp8.show();
        var cmp9 = Ext.create('istsos.view.config', {
            renderTo: Ext.getBody()
        });
        cmp9.show();
        var cmp10 = Ext.create('istsos.view.geo', {
            renderTo: Ext.getBody()
        });
        cmp10.show();
        var cmp11 = Ext.create('istsos.view.getobservation', {
            renderTo: Ext.getBody()
        });
        cmp11.show();
        var cmp12 = Ext.create('istsos.view.database', {
            renderTo: Ext.getBody()
        });
        cmp12.show();
        var cmp13 = Ext.create('istsos.view.serviceurl', {
            renderTo: Ext.getBody()
        });
        cmp13.show();
        var cmp14 = Ext.create('istsos.view.procedure', {
            renderTo: Ext.getBody()
        });
        cmp14.show();
        var cmp15 = Ext.create('istsos.view.newservice', {
            renderTo: Ext.getBody()
        });
        cmp15.show();
        var cmp16 = Ext.create('istsos.view.FormDataQuality', {
            renderTo: Ext.getBody()
        });
        cmp16.show();
        var cmp17 = Ext.create('istsos.view.ObservationEditor', {
            renderTo: Ext.getBody()
        });
        cmp17.show();
        var cmp18 = Ext.create('istsos.view.ObservationEditorColumn', {
            renderTo: Ext.getBody()
        });
        cmp18.show();
        var cmp19 = Ext.create('istsos.view.serviceconfig', {
            renderTo: Ext.getBody()
        });
        cmp19.show();
        var cmp20 = Ext.create('istsos.view.status', {
            renderTo: Ext.getBody()
        });
        cmp20.show();
        var cmp21 = Ext.create('istsos.view.proceduresList', {
            renderTo: Ext.getBody()
        });
        cmp21.show();
        var cmp22 = Ext.create('istsos.view.obsPropEditor', {
            renderTo: Ext.getBody()
        });
        cmp22.show();
        var cmp23 = Ext.create('istsos.view.uomsEditor', {
            renderTo: Ext.getBody()
        });
        cmp23.show();
        var cmp24 = Ext.create('istsos.view.qualityindexEditor', {
            renderTo: Ext.getBody()
        });
        cmp24.show();
        var cmp25 = Ext.create('istsos.view.serviceEditor', {
            renderTo: Ext.getBody()
        });
        cmp25.show();
        var cmp26 = Ext.create('istsos.view.offeringsEditor', {
            renderTo: Ext.getBody()
        });
        cmp26.show();
        var cmp27 = Ext.create('istsos.view.MainMenu2', {
            renderTo: Ext.getBody()
        });
        cmp27.show();
        var cmp28 = Ext.create('istsos.view.ObservationEditorAdvancedOperations', {
            renderTo: Ext.getBody()
        });
        cmp28.show();
        var cmp29 = Ext.create('istsos.view.Calc', {
            renderTo: Ext.getBody()
        });
        cmp29.show();
        var cmp30 = Ext.create('istsos.view.CheckColumn', {
            renderTo: Ext.getBody()
        });
        cmp30.show();
        var cmp31 = Ext.create('istsos.view.ChartContainer', {
            renderTo: Ext.getBody()
        });
        cmp31.show();
        var cmp32 = Ext.create('istsos.view.TestCsv', {
            renderTo: Ext.getBody()
        });
        cmp32.show();
        var cmp33 = Ext.create('istsos.view.Viewer', {
            renderTo: Ext.getBody()
        });
        cmp33.show();
        var cmp34 = Ext.create('istsos.view.Editor1', {
            renderTo: Ext.getBody()
        });
        cmp34.show();
    }
});
