/*
 * File: app/view/testColumn.js
 * Date: Tue Mar 20 2012 09:46:26 GMT+0100 (CET)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.testColumn', {
    extend: 'MyApp.view.ui.testColumn',

    initComponent: function() {
        
        Ext.create('MyApp.store.testColumnStore');
        
        var me = this;
        me.callParent(arguments);
    }
});