/*
 * File: app/store/uomStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('istsosStatus.store.uomStore', {
    extend: 'Ext.data.Store',

    requires: [
        'istsosStatus.model.UomModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            filterOnLoad: false,
            model: 'istsosStatus.model.UomModel',
            sortOnLoad: false,
            storeId: 'uomStore',
            data: [
                {
                    uom: 's'
                },
                {
                    uom: 'min'
                },
                {
                    uom: 'hour'
                },
                {
                    uom: 'day'
                }
            ]
        }, cfg)]);
    }
});